### ISSUE TITLE
[Feature Request] Dark Mode for HTML version

### ISSUE THREAD

**Issue by kiryph** [frankluebeck/GAPDoc#75]
If a dark mode is added, the already existing style menu

![Screenshot 2024-07-19 at 17 12 45](https://github.com/user-attachments/assets/f12b405a-844b-49e9-9c60-ffa58153700a)

 could offer three options regarding the appearance:

1. light
2. dark
3. system

**Comment by kiryph** [comment]
My first approach (the colors still need improvement):

## File `chooser.html`

```diff
diff --git a/styles/chooser.html b/styles/chooser.html
index db786c9..b99e521 100644
--- a/styles/chooser.html
+++ b/styles/chooser.html
@@ -25,7 +25,7 @@ function currval(nam) {

 <!-- find style from current values in form -->
 function getstyle() {
-  var choices = ["toggle","colorprompt","tocside","font","justify"];
+  var choices = ["toggle","colorprompt","tocside","font","justify","appearance"];
   var style = "";
   for (var i=0; choices.length > i; i++) {
     var a = currval(choices[i]);
@@ -55,15 +55,29 @@ function resetf() {
 <!-- initialize form from GAPDocStyle cookie -->
 function initform() {
   var style = valueString(document.cookie, "GAPDocStyle");
-  if (style != 0 && style.length > 0 && style.length != "default") {
+  if (style == 0 || style == "default")
+    // Add dark style following OS setting, if there is no style or default style
+    document.writeln('<style type="text/css">@import "dark.css" (prefers-color-scheme: dark);</style>');
+  if (style != 0 && style.length > 0 && style != "default") {
     stlist = style.split(",");
     var chform = document.forms[0].elements;
+    var appearancesetting = false;
     for (var i=0; chform.length > i; i++) {
       if (chform[i].type == "radio") {
         for (var j=0; stlist.length > j; j++) {
+          if (stlist[j] == "dark" || stlist[j] == "light") {
+            appearancesetting = true;
+          }
+          if (stlist[j] == "dark") {
+            document.writeln('<style type="text/css">@import "dark.css";</style>');
+          }
           if (chform[i].value == stlist[j])
             chform[i].checked = true;
         }
+        // if the user changes non-default values except for appearance
+        if (appearancesetting == false) {
+          document.writeln('<style type="text/css">@import "dark.css" (prefers-color-scheme: dark);</style>');
+        }
       }
     }
   }
@@ -119,6 +133,15 @@ justified (default) &nbsp;&nbsp;&nbsp;
 <input type="radio" name="justify" value="ragged"
 onclick="javascript:f()"/> ragged right
 </p>
+<p>
+Appearance:
+<input type="radio" name="appearance" value="" checked="checked"
+onclick="javascript:f()"/> system (default) &nbsp;&nbsp;&nbsp;
+<input type="radio" name="appearance" value="light"
+onclick="javascript:f()"/> light
+<input type="radio" name="appearance" value="dark"
+onclick="javascript:f()"/> dark
+</p>
 </form>
 <p>
 <a name="backLINK" href=""><strong>Apply settings to last page.</strong></a>
```

### Screenshots of `chooser.html`

#### Light version

<img width="796" height="369" alt="Image" src="https://github.com/user-attachments/assets/b3f874aa-3e5d-4a7d-a8c7-725def4b3f01" />

#### Dark version

<img width="798" height="365" alt="Image" src="https://github.com/user-attachments/assets/4fa62fc5-b0e8-4b98-9b54-b1645d8a6b5c" />

## File `manual.js`
```diff
diff --git a/styles/manual.js b/styles/manual.js
index 627cf94..4bc9995 100644
--- a/styles/manual.js
+++ b/styles/manual.js
@@ -55,6 +55,9 @@ function overwriteStyle() {
   /* otherwise check cookie */
   if (style == 0)
     style = valueString(document.cookie, "GAPDocStyle");
+  if (style == 0 || style == "default")
+    // Add dark style following OS setting, if there is no style or default style
+    document.writeln('<style type="text/css">@import "dark.css" (prefers-color-scheme: dark);</style>');
   if (style == 0)
     return;
   if (style == "default")
@@ -67,16 +70,24 @@ function overwriteStyle() {
     for (var i=0; i+3 < here.length; i++)
       path = path+"/"+here[i];
     */
+    var appearancesetting = false;
     document.cookie = "GAPDocStyle="+style+";Path="+path;
     /* split into names of style files */
     var stlist = style.split(",");
     /* read style's css and js files */
     for (var i=0; i < stlist.length; i++) {
+      if (stlist[i] == "dark" || stlist[i] == "light") {
+        appearancesetting = true;
+      }
       document.writeln('<link rel="stylesheet" type="text/css" href="'+
                                                          stlist[i]+'.css" />');
       document.writeln('<script src="'+stlist[i]+
                                       '.js" type="text/javascript"></script>');
     }
+    // if the user changes non-default values except for appearance
+    if (appearancesetting == false) {
+      document.writeln('<style type="text/css">@import "dark.css" (prefers-color-scheme: dark);</style>');
+    }
   }
 }
```

## File `dark.css`

<details><summary><tt>styles/dark.css</tt></summary>
<p>

```css
/* dark.css                                             Frank Lübeck */
/* This is the dark CSS style sheet for GAPDoc HTML manuals.        */

/* colors */
body { 
  background: #121212 ; 
  color: #eee; 
}

a:link { 
  color: #576CAD; 
}

a:visited { 
  color: #576CAD; 
}

a:active { 
  color: #eee; 
}

a:hover {
  background: #eeeeee;
}

pre { 
  color:black;
}

tt,code { 
  color: #eee; }

/* layout for the definitions of functions, variables, ...  */
div.func {
  background: #909090; 
}

/* general and special table settings */
table {
}

td, th {
} 

table.func { 
}

table.func td.tdright {
}

/* Example elements (for old converted manuals, now in div+pre */
table.example {
  background: #efefef; 
}
table.example td {
}
/* becomes ... */
div.example {
  background: #efefef;
  color: black;
}

/* Links to chapters in all files at top and bottom. */
/* If there are too many chapters then use 'display: none' here. */
div.chlinktop {
  background: #B5B5B5; 
  color: black;
}

div.chlinktop a {
}

div.chlinktop a:hover {
 background: #ffffff;
}

div.chlinkbot {
  background: #B5B5B5; 
  color: black;
}

div.chlinkbot a {
}

span.chlink1 {
}

/* and this is for  the "Top", "Prev", "Next" links */
div.chlinkprevnexttop {
  background: #B5B5B5; 
  color: black;
}

div.chlinkprevnexttop a:hover {
  background: #ffffff;
}

div.chlinkprevnextbot {
  background: #B5B5B5; 
  color: black;
}

div.chlinkprevnextbot a:hover {
  background: #ffffff;
}

div.ContChap div.ContSect:hover div.ContSSBlock {
  background: #eeeeee;
  border-color: #666666;
  color: #000000;
}

div.ContSSBlock a:hover {
  background: #ffffff;
}

/* and here for the side menu of contents in the chapter files */
div.ChapSects {
}

div.ChapSects a:hover {
  background: #eeeeee;
}

div.ChapSects a:hover {
  background: #eeeeee;
  color: #000000;
}

div.ChapSects div.ContSect:hover div.ContSSBlock {
  background: #B5B5B5;
  border-color: #666666;
  color: #000000;
}

div.ChapSects div.ContSect:hover div.ContSSBlock a {
}

div.ChapSects div.ContSect:hover div.ContSSBlock a:hover {
  background: #828282;
}

div.ContSect {
}

div.ChapSects {
}

/* Table elements */
table.GAPDocTable {
  border-color: black;
}

table.GAPDocTable  td, table.GAPDocTable  th {
  border-color: #555555;
}

table.GAPDocTablenoborder  td, table.GAPDocTable  th {
  border-color: #555555;
}

/* Colors and fonts can be overwritten for some types of elements.  */
/* Verb elements */
pre.normal {
  color: #eee;
}

/* Func-like  elements and Ref to Func-like */
code.func {
  color: #eee;
}

/* K elements */
code.keyw {
  color: #983D3D;
}

/* F elements */
code.file {
  color: #8e4510;
}

/* Arg elements */
var.Arg {
  color: #006600;
}

/* colors for ColorPrompt like examples */
span.GAPprompt {
  color: #000097;
}

span.GAPbrkprompt {
  color: #970000;
}

span.GAPinput {
  color: #970000;
}

/* Bib entries */
span.BibKey {
  color: #005522;
}

/* for light and dark mode pictures */
.only-on-dark {
  display: block;
}

.only-on-light {
  display: none;
}

```
</p>
</details> 


## Screenshot of example GAPDoc documentation

<img width="872" height="1144" alt="Image" src="https://github.com/user-attachments/assets/44297cff-207e-4f41-9f4e-c8acdaa0193b" />


## Light and Dark Pictures

Add to `manual.css`:
```diff
diff --git a/styles/manual.css b/styles/manual.css
index cb1c7ce..768acce 100644
--- a/styles/manual.css
+++ b/styles/manual.css
@@ -477,7 +477,13 @@ span.BibNote {
 span.BibHowpublished {
 }

+/* for light and dark mode pictures */
+.only-on-dark {
+  display: none;
+}
+
```

Add to `dark.css`
```css
/* for light and dark mode pictures */
.only-on-dark {
  display: block;
}

.only-on-light {
  display: none;
}
```

Add the image as following:
```xml
<Alt Only="HTML"><![CDATA[
<div style='text-align:center; margin: 10px'>
    <img class="only-on-light" src='images/light.png'>
    <img class="only-on-dark" src='images/dark.png'>
</div>
]]></Alt>
```
